application: velourrpg
version: 1
runtime: go
api_version: go1

handlers:
- url: /assets
  static_dir: client/assets
- url: /js
  static_dir: client/js
- url: /css
  static_dir: client/css
- url: /.*
  script: _go_app
